// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_WEB_API']!}',
    appId: '1:501019962241:web:542a2dd153801b26c85680',
    messagingSenderId: '501019962241',
    projectId: 'medicine-proj',
    authDomain: 'medicine-proj.firebaseapp.com',
    storageBucket: 'medicine-proj.appspot.com',
    measurementId: 'G-WWJH9LJ42W',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_ANDROID_API']!}',
    appId: '1:501019962241:android:d122b59e8ab319f0c85680',
    messagingSenderId: '501019962241',
    projectId: 'medicine-proj',
    storageBucket: 'medicine-proj.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_APPLE_API']!}',
    appId: '1:501019962241:ios:a9a288d157efed73c85680',
    messagingSenderId: '501019962241',
    projectId: 'medicine-proj',
    storageBucket: 'medicine-proj.appspot.com',
    iosClientId: '501019962241-jv189goa370gbq3dgj3sek5p7gh519ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicCountFe',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_APPLE_API']!}',
    appId: '1:501019962241:ios:8405e9014bc5c53bc85680',
    messagingSenderId: '501019962241',
    projectId: 'medicine-proj',
    storageBucket: 'medicine-proj.appspot.com',
    iosClientId: '501019962241-gl04v5to20t72l431feijmbl1rchdcvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicCountFe.RunnerTests',
  );
}
